[[buildpacks]]
  uri = "maven-buildpack"
  id = "mskj.cmbc.com.cn.buildpacks.java.maven"
[[buildpacks]]
  uri = "gradle-buildpack"
  id = "mskj.cmbc.com.cn.buildpacks.java.gradle"
[[order]]
  [[order.group]]
    id = "mskj.cmbc.com.cn.buildpacks.java.gradle"
    version = "0.0.1"
[[order]]
  [[order.group]]
    id = "mskj.cmbc.com.cn.buildpacks.java.maven"
    version = "0.0.1"
[stack]
  id = "mskj.cmbc.com.cn.java8"
  build-image = "mskj/java8-builder-base:latest"
  run-image = "mskj/java8-base:latest"
[lifecycle]
  version="0.5.0"
